In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
# read data
file1 = "Gender_StatsEXCEL.xlsx"
file2 = "CLASS.xls"  #this file maps countries to geographical regions and facilitates comparison in plots
data1 = pd.read_excel(file1, sheet_name=0)
data2 = pd.read_excel(file2, sheet_name=0, skiprows=4, usecols = [2,5,6])

In [ ]:
data2.dropna(axis=0, inplace=True) #extract only rows that contain country-region pairs for mapping with data1 
data2=data2.iloc[1:] #drop blank first row
countries = data2['Economy'].unique()
regions= data2['Region'].unique()
incomes = data2['Income group'].unique()
regions_incomes = np.append(regions, incomes)
regions_incomes = np.append(regions_incomes, "World")

In [3]:
#define function to create subsets of data of interest from data1 
def subset_data(data, subset_group, start, end):

    # subset data to include only subset group
    df = data[data['Country Name'].isin(subset_group)]

    #subset data to include only specified time frame
    years_to_keep = [str(year) for year in list(range(start,end+1))]
    cols_to_keep = ['Country Name','Indicator Name'] + years_to_keep
    df = df[cols_to_keep]


    # select indicators of interest, based on indicators explored in SG plots and indicators of interest
    selected_indicators = ['GNI per capita, Atlas method (current US$)',
    'Expected years of schooling, female',
    'Expected years of schooling, male',
    'Tertiary education, academic staff (% female)',
    'Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)',
    'Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)',
    'Literacy rate, adult female (% of females ages 15 and above)',
    'Literacy rate, adult male (% of males ages 15 and above)',
    'School enrollment, tertiary (gross), gender parity index (GPI)',
    'Proportion of women subjected to physical and/or sexual violence in the last 12 months (% of women age 15-49)',
    'Female professional and technical workers (% of total)',
    'Proportion of seats held by women in national parliaments (%)',
    'Proportion of women in ministerial level positions (%)',
    'Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)',
    'Female headed households (% of households with a female head)',
    'Women who were first married by age 18 (% of women ages 20-24)',
    'Adolescent fertility rate (births per 1,000 women ages 15-19)',
    'Fertility rate, total (births per woman)',
    'Maternal leave benefits (% of wages paid)',
    'Maternity leave (days paid)',
    'Firms with female participation in ownership (% of firms)',
    'Firms with female top manager (% of firms)',
    'Female share of employment in senior and middle management (%)',
    'Ratio of female to male labor force participation rate (%) (modeled ILO estimate)',
    'Unemployment, female (% of female labor force) (modeled ILO estimate)',
    'Unemployment, male (% of male labor force) (modeled ILO estimate)']

    #subset data based on selected indicators
    df = df[df['Indicator Name'].isin(selected_indicators)] 

    #get column names corresponding to years 
    years = [str(x) for x in range(start,end+1)]

    # reshape df into df1: get indicators as column headers and years as observations. Exclude redundant columns such as country code and indicator code
    df1 = pd.melt(df, id_vars=['Country Name','Indicator Name'], value_vars = years, 
            var_name='Year', value_name='Value')
    df1 = df1.set_index(['Country Name','Year','Indicator Name']).unstack(level=-1)
    df1.reset_index(inplace=True)
    df1.columns = df1.columns.droplevel(0)
    df1.columns = ['Country', 'Year']+(list(df1.columns[2:])) #rename columns

    # create new variables for gender comparison - calculate the parity index
    df1['Ratio of female to male tertiary educational attainment rate (GPI) (%)'] = 100*df1['Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)']/df1['Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)']
    df1['Ratio of female to male expected years of schooling (%)'] = 100*df1['Expected years of schooling, female']/df1['Expected years of schooling, male']
    df1['Literacy rate (ages 15 and above) (GPI)(%)'] = 100*df1['Literacy rate, adult female (% of females ages 15 and above)']/df1['Literacy rate, adult male (% of males ages 15 and above)']
    df1.rename(columns={'Ratio of female to male labor force participation rate (%) (modeled ILO estimate)':
                   'Labor force participation rate (ages 15 and above) (%) (GPI)'})
    df1['Ratio of female to male unemployment (%)'] = 100*df1['Unemployment, female (% of female labor force) (modeled ILO estimate)']/df1['Unemployment, male (% of male labor force) (modeled ILO estimate)']
    df1['School enrollment, tertiary (gross), gender parity index (GPI)(%)'] = 100 * df1['School enrollment, tertiary (gross), gender parity index (GPI)']
    
    #drop redundant columns
    columns_to_drop = ['Expected years of schooling, female', 
                   'Expected years of schooling, male',
                   'Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)',
                   'Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)',
                   'Literacy rate, adult female (% of females ages 15 and above)',
                   'Literacy rate, adult male (% of males ages 15 and above)',
                   'Unemployment, female (% of female labor force) (modeled ILO estimate)',
                   'Unemployment, male (% of male labor force) (modeled ILO estimate)',
                        'School enrollment, tertiary (gross), gender parity index (GPI)']

    df1.drop(columns_to_drop, axis = 1, inplace=True)

    #shorten column names
    df1.columns = ['Country', 'Year',
    'Adolescent fertility rate (per 1,000)',
    'Proportion of households with female head (%)',
    'Professional and technical workers (% female)',
    'Employment in senior and middle management (% female)',
    'Fertility rate',
    'Firms with female participation in ownership (% of firms)',
    'Firms with female top manager (% of firms)',
    'GNI per capita(current US$)',
    'Maternity leave (days paid)',
    'National parliament seats (% female)',
    'Ministerial level positions (% female)',
    'Proportion of women subjected to physical/sexual violence in last 12 months (%)',
    'Labor force participation rate (GPI) (%)',
    'Tertiary education, academic staff (% female)',
    'Proportion of women participating in the three decisions (%)',
    'Women who were first married by age 18 (% of women ages 20-24)',
    'Ratio of female to male tertiary educational attainment rate (GPI) (%)',
    'Ratio of female to male expected years of schooling (%)',
    'Literacy rate (ages 15 and above) (GPI)(%)',
    'Ratio of female to male unemployment (%)',
    'School enrollment, tertiary (gross),(GPI) (%)']
    
    #set year column to numeric and take log of GNI for comparability to other data as GNI values are of magnitudes larger than other indicators
    df1['Year']=pd.to_numeric(df1['Year'])
    df1['log(GNI)'] = df1['GNI per capita(current US$)'].apply(lambda x: math.log(x)) 

    return df1

In [4]:
#define function to drop columns if the number of NaN values for that column exceed a threshold (i.e. beyond which it may be useless for scatter plot)
def dropcols(data, threshold):

    columns_to_drop = data.columns[(data.isnull().sum()/len(data)) > threshold]

    return data.drop(columns_to_drop, axis=1)

In [6]:

# get country gender data (Subset1)
start = 2012
end = 2017
df = subset_data(data1,countries,start,end)

#map countries to geographical region (to facilitate scatterplot analysis), drop redundant columns
df = df.merge(data2[['Economy','Region']], how='left', left_on = 'Country', right_on = "Economy")
df.drop('Economy', inplace=True, axis=1) 

#fill NA values and sort by region (so the legend in plot is alphabetical)
#define new dataframe country_data_m for filled table
df1 = df.groupby('Country').apply(lambda x:x.fillna(method='pad')) 
df1.sort_values(by='Region', inplace=True)

# Drop indicators for which there are still many NaNs despite forward filling. 
# Indicators with more than 50% NaN values are dropped as they will be less useful for scatterplots
threshold = 0.5
columns_to_drop =  df1.columns[(df1.isnull().sum()/len(df1)) > threshold]
country_data = df1.drop(columns_to_drop, axis=1)

In [7]:
def get_cluster_plotdata(data1, data2):
    #define subset_group
    
    
    #get cluster data
    start = 2001
    end = 2017
    cluster_data = subset_data(data1, regions_incomes, start, end)

    #drop indicators with more than 60% NaN values
    threshold = 0.6
    cluster_data = dropcols(cluster_data, threshold)
    
    return cluster_data

In [20]:
df2.head()

,Country,Year,"Adolescent fertility rate (per 1,000)",Fertility rate,GNI per capita(current US$),National parliament seats (% female),Ministerial level positions (% female),Labor force participation rate (GPI) (%),"Tertiary education, academic staff (% female)",Ratio of female to male expected years of schooling (%),Literacy rate (ages 15 and above) (GPI)(%),Ratio of female to male unemployment (%),"School enrollment, tertiary (gross),(GPI) (%)",log(GNI)
0,East Asia & Pacific,2001,19.606005,1.780181,3917.825733,16.565385,NaN,79.717512,35.33900,96.383148,92.753624,87.170515,82.828,8.273292
1,East Asia & Pacific,2002,19.125343,1.780793,3872.142833,17.121009,NaN,79.487742,35.54910,96.728044,93.056798,86.718368,86.009,8.261563
2,East Asia & Pacific,2003,18.586627,1.783416,4052.413770,16.056573,NaN,79.272864,35.56887,96.770235,93.406318,87.318114,86.797,8.307068
3,East Asia & Pacific,2004,18.190692,1.787019,4555.643831,16.613689,NaN,79.040789,35.74409,97.735332,93.737552,88.499101,89.588,8.424122
4,East Asia & Pacific,2005,17.994057,1.786377,4984.859427,16.928497,9.460362,78.888109,37.31749,98.077828,93.985488,89.542826,90.504,8.514160