In [1]:
import os
import pandas as pd
import numpy as np
from bokeh.io import curdoc
from bokeh.models.widgets import Tabs

from scripts.transform import subset_data
from scripts.scatter import scatter_tab
from scripts.line import line_tab


# In[39]:


#path = os.getcwd()
file1 = "Gender_StatsEXCEL.xlsx"
file2 = "CLASS.xls"
#filepath1  = os.path.join(path,'data',file1)
#filepath2  = os.path.join(path,'data',file2)
filepath1 = "data/"+file1
filepath2 = "data/"+file2

# In[40]:


data1 = pd.read_excel(filepath1, sheet_name=0)
data2 = pd.read_excel(filepath2, sheet_name=0, skiprows=4, usecols = [2,5,6])

In [2]:
data1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Arab World,ARB,"Access to anti-retroviral drugs, female (%)",SH.HIV.ARTC.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"Access to anti-retroviral drugs, male (%)",SH.HIV.ARTC.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,13.775815,NaN,NaN,22.079350,NaN,NaN,25.635403
3,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.377668,NaN,NaN,37.790764,NaN,NaN,48.328518
4,Arab World,ARB,"Adjusted net enrollment rate, primary, female ...",SE.PRM.TENR.FE,NaN,NaN,NaN,NaN,NaN,NaN,...,82.114799,82.397430,83.632736,83.027420,83.984322,82.891869,82.462196,82.840759,82.925117,NaN
5,Arab World,ARB,"Adjusted net enrollment rate, primary, male (%...",SE.PRM.TENR.MA,NaN,NaN,NaN,NaN,NaN,NaN,...,87.182999,87.422943,88.205338,87.481712,86.838631,85.528038,84.937042,85.331963,85.266518,NaN
6,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,134.223612,134.838634,135.570905,135.444640,135.274904,134.947174,...,50.316994,50.104610,49.900118,49.723757,49.539074,49.111244,48.647539,48.114552,47.440069,NaN
7,Arab World,ARB,"Age at first marriage, female",SP.DYN.SMAM.FE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Arab World,ARB,"Age at first marriage, male",SP.DYN.SMAM.MA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Arab World,ARB,Age dependency ratio (% of working-age populat...,SP.POP.DPND,88.205810,89.644734,90.944498,92.063631,92.892881,93.364459,...,64.235293,63.365027,62.694715,62.341696,62.168854,62.118188,62.089858,62.017234,62.057475,61.916180
10,Arab World,ARB,"Age population, age 0, female, interpolated",SP.POP.AG00.FE.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Arab World,ARB,"Age population, age 0, male, interpolated",SP.POP.AG00.MA.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Arab World,ARB,"Age population, age 01, female, interpolated",SP.POP.AG01.FE.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Arab World,ARB,"Age population, age 01, male, interpolated",SP.POP.AG01.MA.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Arab World,ARB,"Age population, age 02, female, interpolated",SP.POP.AG02.FE.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Arab World,ARB,"Age population, age 02, male, interpolated",SP.POP.AG02.MA.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Arab World,ARB,"Age population, age 03, female, interpolated",SP.POP.AG03.FE.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Arab World,ARB,"Age population, age 03, male, interpolated",SP.POP.AG03.MA.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Arab World,ARB,"Age population, age 04, female, interpolated",SP.POP.AG04.FE.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Arab World,ARB,"Age population, age 04, male, interpolated",SP.POP.AG04.MA.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Arab World,ARB,"Age population, age 05, female, interpolated",SP.POP.AG05.FE.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Arab World,ARB,"Age population, age 05, male, interpolated",SP.POP.AG05.MA.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Arab World,ARB,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,47.689955,47.468025,47.245496,47.014786,46.770214,46.502229,...,27.486639,27.535705,27.564317,27.532156,27.412583,27.190502,26.860505,26.431200,25.927766,NaN
23,Arab World,ARB,Births attended by skilled health staff (% of ...,SH.STA.BRTC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,82.780750,NaN,NaN,NaN
24,Arab World,ARB,"Cause of death, by communicable diseases, ages...",SH.DTH.COMM.1534.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,30.517146,NaN,NaN,NaN,NaN,25.510667,NaN,NaN
25,Arab World,ARB,"Cause of death, by communicable diseases, ages...",SH.DTH.COMM.1534.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,11.436034,NaN,NaN,NaN,NaN,8.576893,NaN,NaN
26,Arab World,ARB,"Cause of death, by communicable diseases, ages...",SH.DTH.COMM.3559.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,11.911208,NaN,NaN,NaN,NaN,10.632703,NaN,NaN
27,Arab World,ARB,"Cause of death, by communicable diseases, ages...",SH.DTH.COMM.3559.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.233991,NaN,NaN,NaN,NaN,8.103229,NaN,NaN
28,Arab World,ARB,"Cause of death, by injury, ages 15-34, female ...",SH.DTH.INJR.1534.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,22.558187,NaN,NaN,NaN,NaN,33.533685,NaN,NaN
29,Arab World,ARB,"Cause of death, by injury, ages 15-34, male (%...",SH.DTH.INJR.1534.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,55.261941,NaN,NaN,NaN,NaN,64.657622,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133311,Zimbabwe,ZWE,Women who own a house both alone and jointly (...,SG.OWN.HSAJ.FE.Q3.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.300000,NaN,NaN,NaN,1.300000,NaN,NaN
133312,Zimbabwe,ZWE,Women who own a house both alone and jointly (...,SG.OWN.HSAJ.FE.Q4.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.900000,NaN,NaN,NaN,1.200000,NaN,NaN
133313,Zimbabwe,ZWE,Women who own a house both alone and jointly (...,SG.OWN.HSAJ.FE.Q5.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,3.400000,NaN,NaN
133314,Zimbabwe,ZWE,Women who own a house jointly (% of women age ...,SG.OWN.HSJT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,26.500000,NaN,NaN,NaN,29.300000,NaN,NaN
133315,Zimbabwe,ZWE,Women who own a house jointly (% of women age ...,SG.OWN.HSJT.FE.Q1.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,47.600000,NaN,NaN,NaN,45.700000,NaN,NaN
133316,Zimbabwe,ZWE,Women who own a house jointly (% of women age ...,SG.OWN.HSJT.FE.Q2.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,39.800000,NaN,NaN,NaN,40.900000,NaN,NaN
133317,Zimbabwe,ZWE,Women who own a house jointly (% of women age ...,SG.OWN.HSJT.FE.Q3.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,26.800000,NaN,NaN,NaN,31.700000,NaN,NaN
133318,Zimbabwe,ZWE,Women who own a house jointly (% of women age ...,SG.OWN.HSJT.FE.Q4.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,15.500000,NaN,NaN,NaN,18.000000,NaN,NaN
133319,Zimbabwe,ZWE,Women who own a house jointly (% of women age ...,SG.OWN.HSJT.FE.Q5.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,12.600000,NaN,NaN,NaN,18.800000,NaN,NaN
133320,Zimbabwe,ZWE,Women who own land alone (% of women age 15-49),SG.OWN.LDAL.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.900000,NaN,NaN,NaN,3.900000,NaN,NaN
133321,Zimbabwe,ZWE,Women who own land alone (% of women age 15-49...,SG.OWN.LDAL.FE.Q1.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,15.300000,NaN,NaN,NaN,7.700000,NaN,NaN
133322,Zimbabwe,ZWE,Women who own land alone (% of women age 15-49...,SG.OWN.LDAL.FE.Q2.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,13.700000,NaN,NaN,NaN,4.100000,NaN,NaN
133323,Zimbabwe,ZWE,Women who own land alone (% of women age 15-49...,SG.OWN.LDAL.FE.Q3.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.500000,NaN,NaN,NaN,4.900000,NaN,NaN
133324,Zimbabwe,ZWE,Women who own land alone (% of women age 15-49...,SG.OWN.LDAL.FE.Q4.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.400000,NaN,NaN,NaN,2.300000,NaN,NaN
133325,Zimbabwe,ZWE,Women who own land alone (% of women age 15-49...,SG.OWN.LDAL.FE.Q5.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,1.800000,NaN,NaN
133326,Zimbabwe,ZWE,Women who own land both alone and jointly (% o...,SG.OWN.LDAJ.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.700000,NaN,NaN,NaN,1.600000,NaN,NaN
133327,Zimbabwe,ZWE,Women who own land both alone and jointly (% o...,SG.OWN.LDAJ.FE.Q1.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.500000,NaN,NaN,NaN,1.700000,NaN,NaN
133328,Zimbabwe,ZWE,Women who own land both alone and jointly (% o...,SG.OWN.LDAJ.FE.Q2.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.100000,NaN,NaN,NaN,1.400000,NaN,NaN
133329,Zimbabwe,ZWE,Women who own land both alone and jointly (% o...,SG.OWN.LDAJ.FE.Q3.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.600000,NaN,NaN,NaN,1.400000,NaN,NaN
133330,Zimbabwe,ZWE,Women who own land both alone and jointly (% o...,SG.OWN.LDAJ.FE.Q4.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,1.200000,NaN,NaN
133331,Zimbabwe,ZWE,Women who own land both alone and jointly (% o...,SG.OWN.LDAJ.FE.Q5.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.500000,NaN,NaN,NaN,2.200000,NaN,NaN
133332,Zimbabwe,ZWE,Women who own land jointly (% of women age 15-49),SG.OWN.LDJT.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,25.400000,NaN,NaN,NaN,24.900000,NaN,NaN
133333,Zimbabwe,ZWE,Women who own land jointly (% of women age 15-...,SG.OWN.LDJT.FE.Q1.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,43.700000,NaN,NaN,NaN,39.500000,NaN,NaN
133334,Zimbabwe,ZWE,Women who own land jointly (% of women age 15-...,SG.OWN.LDJT.FE.Q2.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,37.500000,NaN,NaN,NaN,37.900000,NaN,NaN
133335,Zimbabwe,ZWE,Women who own land jointly (% of women age 15-...,SG.OWN.LDJT.FE.Q3.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27.500000,NaN,NaN,NaN,28.800000,NaN,NaN
133336,Zimbabwe,ZWE,Women who own land jointly (% of women age 15-...,SG.OWN.LDJT.FE.Q4.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,15.600000,NaN,NaN,NaN,14.500000,NaN,NaN
133337,Zimbabwe,ZWE,Women who own land jointly (% of women age 15-...,SG.OWN.LDJT.FE.Q5.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,12.100000,NaN,NaN,NaN,13.100000,NaN,NaN
133338,Zimbabwe,ZWE,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.700000,NaN,NaN
133339,Zimbabwe,ZWE,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.100000,NaN,30.500000,NaN,NaN,33.500000,32.400000,NaN,NaN
133340,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,57.400000,57.400000,58.200000,58.400000,58.600000,58.800000,58.900000,58.900000,59.000000,59.100000